//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRN292_LapTopSaleSystemWF_Group4.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ID { get; set; }
        public string image1 { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual Product Product { get; set; }

        public Image(string image1, int? productID)
        {
            this.image1 = image1;
            ProductID = productID;
        }
    }
}
