//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRN292_LapTopSaleSystemWF_Group4.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductDetail()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string Processor { get; set; }
        public string RAM { get; set; }
        public string Screen { get; set; }
        public string Storage { get; set; }
        public string Graphic { get; set; }
        public string Size { get; set; }
        public string OS { get; set; }
        public string Video { get; set; }
        public string Connection { get; set; }
        public string Keyboard { get; set; }
        public string Battery { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
