//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRN292_LapTopSaleSystemWF_Group4.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userId { get; set; }
        public string fullname { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string image { get; set; }
        public Nullable<byte> role { get; set; }
        public Nullable<byte> active { get; set; }
    }
}
